# Generated by Django 5.2.11 on 2026-03-30 11:15

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usage", "0002_alter_appusage_usage_type_dailyappusagetop_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyappusagetop",
            options={"ordering": ["-date", "rank"]},
        ),
        migrations.AlterModelOptions(
            name="dailyusagesummary",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="dailyusagesummary",
            name="goal_achieved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyusagesummary",
            name="goal_exceeded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyusagesummary",
            name="target_minutes_snapshot",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dailyappusagetop",
            name="rank",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyappusagetop",
            unique_together={("user", "date", "rank")},
        ),
        migrations.DeleteModel(
            name="WeeklyUsageGoal",
        ),
    ]
