# Generated by Django 6.0.4 on 2026-04-23 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
        ('wellness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emotionlog',
            options={},
        ),
        migrations.RemoveField(
            model_name='emotionlog',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='emotionlog',
            name='text_original',
        ),
        migrations.AddField(
            model_name='emotionlog',
            name='emotion_label',
            field=models.CharField(default='알 수 없음', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotionlog',
            name='log_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emotionlog',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AiCoachingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_text', models.TextField(blank=True, null=True)),
                ('suggestion_text', models.TextField()),
                ('user_response', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(default='ongoing', max_length=50)),
                ('challenge_type', models.CharField(max_length=50)),
                ('target_app_name', models.CharField(blank=True, max_length=255, null=True)),
                ('target_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usage.appcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField()),
                ('total_usage_minutes', models.IntegerField()),
                ('total_unlocks', models.IntegerField()),
                ('most_used_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usage.appcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'summary_date')},
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_blocked_apps', models.TextField(blank=True, null=True)),
                ('ai_coaching_style', models.CharField(default='neutral', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
