# Generated by Django 6.0.3 on 2026-03-26 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wellness", "0003_alter_dailysummary_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailychallenge",
            name="target_app_name",
        ),
        migrations.RemoveField(
            model_name="dailychallenge",
            name="target_category",
        ),
        migrations.RemoveField(
            model_name="dailychallenge",
            name="target_minutes",
        ),
        migrations.RemoveField(
            model_name="monthlychallenge",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="monthlychallenge",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="monthlychallenge",
            name="status",
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 3, 26, 19, 15, 53, 18581, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("BEGINNER", "초급"),
                    ("INTERMEDIATE", "중급"),
                    ("ADVANCED", "고급"),
                ],
                default="BEGINNER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="points_reward",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="monthlychallenge",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 3, 26, 19, 16, 3, 446168, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monthlychallenge",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("BEGINNER", "초급"),
                    ("INTERMEDIATE", "중급"),
                    ("ADVANCED", "고급"),
                ],
                default="BEGINNER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="monthlychallenge",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="monthlychallenge",
            name="month",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="monthlychallenge",
            name="points_reward",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="monthlychallenge",
            name="year",
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="current_difficulty",
            field=models.CharField(
                choices=[
                    ("BEGINNER", "초급"),
                    ("INTERMEDIATE", "중급"),
                    ("ADVANCED", "고급"),
                ],
                default="BEGINNER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="daily_regen_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="last_regen_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="next_week_difficulty",
            field=models.CharField(
                choices=[
                    ("BEGINNER", "초급"),
                    ("INTERMEDIATE", "중급"),
                    ("ADVANCED", "고급"),
                ],
                default="BEGINNER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="ai_coaching_style",
            field=models.CharField(default="GENTLE", max_length=50),
        ),
    ]
