# Generated by Django 5.2.11 on 2026-03-30 11:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usage", "0003_alter_dailyappusagetop_options_and_more"),
        ("wellness", "0004_remove_dailychallenge_target_app_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailychallenge",
            old_name="date",
            new_name="challenge_date",
        ),
        migrations.RemoveField(
            model_name="dailychallenge",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="dailychallenge",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="dailychallenge",
            name="points_reward",
        ),
        migrations.RemoveField(
            model_name="monthlychallenge",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="monthlychallenge",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="monthlychallenge",
            name="month",
        ),
        migrations.RemoveField(
            model_name="monthlychallenge",
            name="points_reward",
        ),
        migrations.RemoveField(
            model_name="monthlychallenge",
            name="year",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="current_difficulty",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="daily_regen_count",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="last_regen_date",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="next_week_difficulty",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="primary_emotion",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="session_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="generated_by",
            field=models.CharField(
                choices=[
                    ("ai", "AI 생성"),
                    ("system", "시스템 생성"),
                    ("manual", "수동 생성"),
                ],
                default="ai",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="reward_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "진행중"),
                    ("completed", "완료"),
                    ("failed", "실패"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="target_app_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="target_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usage.appcategory",
            ),
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="target_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailytip",
            name="related_emotion",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="emotionlog",
            name="input_method",
            field=models.CharField(
                choices=[("text", "직접 입력"), ("quick_button", "빠른 버튼")],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="monthlychallenge",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monthlychallenge",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monthlychallenge",
            name="end_date",
            field=models.DateField(default=datetime.date(2026, 3, 31)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monthlychallenge",
            name="generated_by",
            field=models.CharField(
                choices=[
                    ("ai", "AI 생성"),
                    ("system", "시스템 생성"),
                    ("manual", "수동 생성"),
                ],
                default="ai",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="monthlychallenge",
            name="reward_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthlychallenge",
            name="start_date",
            field=models.DateField(default=datetime.date(2026, 3, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monthlychallenge",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "진행중"),
                    ("completed", "완료"),
                    ("failed", "실패"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pointhistory",
            name="daily_challenge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wellness.dailychallenge",
            ),
        ),
        migrations.AddField(
            model_name="pointhistory",
            name="monthly_challenge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wellness.monthlychallenge",
            ),
        ),
        migrations.AddField(
            model_name="userlevel",
            name="last_level_up_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="daily_target_minutes",
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="preferred_challenge_difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "초급"),
                    ("intermediate", "중급"),
                    ("advanced", "고급"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="push_notification_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="usage_alert_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.CharField(
                choices=[("user", "사용자"), ("ai", "AI")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "초급"),
                    ("intermediate", "중급"),
                    ("advanced", "고급"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="monthlychallenge",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "초급"),
                    ("intermediate", "중급"),
                    ("advanced", "고급"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="ai_coaching_style",
            field=models.CharField(default="neutral", max_length=50),
        ),
    ]
