# Generated by Django 5.2.11 on 2026-03-23 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_created_at_alter_user_avatar_url_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("push_notification_enabled", models.BooleanField(default=True)),
                ("usage_alert_enabled", models.BooleanField(default=True)),
                ("night_reminder_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="provider",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("google", "Google"),
                    ("kakao", "Kakao"),
                    ("firebase", "Firebase"),
                    ("firebase_password", "Firebase Password"),
                ],
                default="local",
                help_text="로그인 제공자(local/google/kakao/firebase 등)",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="provider_uid",
            field=models.CharField(
                blank=True,
                help_text="소셜 로그인 제공자의 사용자 고유 ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_uid"),
                name="unique_provider_and_provider_uid",
            ),
        ),
        migrations.AddField(
            model_name="usernotificationsetting",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_setting",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
